/**
 * Auto-generated model catalog.
 *
 * Generated by: @coohu/llms/scripts/generate-models.ts
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
import type { ModelInfo } from "@coohu/shared";
/**
 * Model list auto-generated for built-in providers
 * listed in @coohu/llms/src/providers/provider-keys.ts
 */
export declare const GENERATED_PROVIDER_MODELS: {
	version: number;
	providers: Record<string, Record<string, ModelInfo>>;
};
